apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
    component: kafka-connector
  name: kafka-connector
  namespace: kubesphere-openfx-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      component: kafka-connector
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      labels:
        app: kafka
        component: kafka-connector
    spec:
      containers:
      - name: kafka
        image: cyy92/kafka-connector:latest
        env:
          - name: gateway_url
            value: "10.0.0.202:31113"
          - name: topics
            value: "faas-request,"
          - name: topic_delimiter
            value: ","
          - name: asynchronous_invocation
            value: "true"
       
