apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: openfx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        command:
          - "prometheus"
          - "--config.file=/etc/prometheus/prometheus.yml"
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 512Mi
        volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus-configuration
          subPath: prometheus.yml
      volumes:
        - name: prometheus-configuration
          configMap:
            name: prometheus-configuration
            items:
              - key: prometheus.yml
                path: prometheus.yml
                mode: 0644

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: openfx
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 31119
  selector:
    app: prometheus


---

kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: prometheus-configuration
  namespace: openfx
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
      external_labels:
          monitor: 'openfx-monitor'
    rule_files:
        - 'alert.rules.yml'
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: "node_exporter"
        scrape_interval: 5s
        static_configs:
          - targets: ['10.0.0.180:9100']
      - job_name: "gateway"
        scrape_interval: 5s
        dns_sd_configs:
          - names: ['fxgateway.openfx']
            port: 10000
            type: A
            refresh_interval: 5s

